# Generated by Django 6.0.3 on 2026-03-19 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_fiscal', models.PositiveIntegerField(unique=True)),
                ('valor_uit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divisor_umbral_depreciacion', models.PositiveIntegerField(default=4)),
                ('es_activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parámetro del Sistema',
                'verbose_name_plural': 'Parámetros del Sistema',
                'db_table': 'inventario_parametrosistema',
                'ordering': ['-anio_fiscal'],
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, editable=False, max_length=300, null=True, verbose_name='Nombre o Denominación')),
                ('grupo_generico', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('clase', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('codigo_patrimonial_base', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Cód. Patrimonial Base')),
                ('correlativo', models.PositiveIntegerField(default=0, verbose_name='Correlativo')),
                ('codigo_patrimonial', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Cód. Patrimonial Completo')),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cód. Interno')),
                ('tipo_cuenta', models.CharField(choices=[('USO_ESTATAL', 'DE USO ESTATAL'), ('USO_PRIVADO', 'DE USO PRIVADO')], default='USO_ESTATAL', max_length=20, verbose_name='Tipo de Cuenta')),
                ('tasa_depreciacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vida_util_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('forma_adquisicion', models.CharField(choices=[('COMPRA', 'Compra'), ('DONACION', 'Donación'), ('FABRICACION', 'Fabricación'), ('PERMUTA', 'Permuta'), ('REPOSICION', 'Reposición'), ('REPRODUCCION', 'Reproducción'), ('SANEAMIENTO', 'Saneamiento')], max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('resolucion_alta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pecosa', models.DateField(blank=True, null=True, verbose_name='Fecha de PECOSA / Salida')),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('CHADARRA', 'Chatarra'), ('RAEE', 'RAEE'), ('BAJA', 'De Baja')], default='BUENO', max_length=15)),
                ('situacion', models.CharField(choices=[('NORMAL', 'Normal'), ('SOBRANTE', 'Sobrante'), ('FALTANTE', 'Faltante')], default='NORMAL', max_length=10, verbose_name='Situación')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensión')),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_fabricacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('otros_detalles', models.TextField(blank=True, help_text='Especificaciones adicionales en formato texto', null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.area')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cuentacontable')),
                ('denominacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='catalogos.denominacion', verbose_name='Denominación')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.local')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.oficina')),
                ('ubicacion_fisica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacion.ubicacionfisica')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal')),
            ],
            options={
                'verbose_name_plural': 'Bienes',
                'db_table': 'inventario_bien',
            },
        ),
        migrations.CreateModel(
            name='HistoricoDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_fiscal', models.PositiveIntegerField()),
                ('valor_adquisicion_h', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciacion_acumulada_h', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_neto_h', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_h', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('CHADARRA', 'Chatarra'), ('RAEE', 'RAEE'), ('BAJA', 'De Baja')], max_length=15)),
                ('oficina_h', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_h', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_cierre', models.DateTimeField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='bienes.bien')),
            ],
            options={
                'verbose_name': 'Histórico de Depreciación',
                'verbose_name_plural': 'Históricos de Depreciación',
                'db_table': 'inventario_historicodepreciacion',
                'ordering': ['-anio_fiscal', 'bien'],
            },
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['codigo_patrimonial'], name='inventario__codigo__53a07f_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['estado'], name='inventario__estado_34b80c_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['codigo_patrimonial', 'estado'], name='inventario__codigo__dd1223_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['estado', 'situacion'], name='inventario__estado_817f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['fecha_adquisicion'], name='inventario__fecha_a_c1d4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['cuenta_contable'], name='inventario__cuenta__033327_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['usuario_asignado'], name='inventario__usuario_89ca28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicodepreciacion',
            unique_together={('bien', 'anio_fiscal')},
        ),
    ]
