# Generated by Django 6.0.3 on 2026-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='situacion',
            field=models.CharField(choices=[('USO', 'En Uso'), ('DESUSO', 'En Desuso')], default='USO', max_length=10, verbose_name='Situación'),
        ),
    ]
