# Generated by Django 6.0.3 on 2026-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_alter_bien_situacion'),
        ('catalogos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['cuenta_contable', 'estado'], include=('valor_adquisicion', 'valor_neto'), name='bien_cuenta_cob_idx'),
        ),
    ]
