# Generated by Django 6.0.3 on 2026-03-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bienes', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traslado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Traslado')),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que registró')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('area_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='organizacion.area', verbose_name='Área Destino')),
                ('area_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='organizacion.area', verbose_name='Área Origen')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='bienes.bien', verbose_name='Bien')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='organizacion.local', verbose_name='Local Destino')),
                ('local_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='organizacion.local', verbose_name='Local Origen')),
                ('oficina_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='organizacion.oficina', verbose_name='Oficina Destino')),
                ('oficina_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='organizacion.oficina', verbose_name='Oficina Origen')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino_ubicacion', to='organizacion.ubicacionfisica', verbose_name='Ubicación Física Destino')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen_ubicacion', to='organizacion.ubicacionfisica', verbose_name='Ubicación Física Origen')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='personal.personal', verbose_name='Usuario Destino')),
                ('usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='personal.personal', verbose_name='Usuario Origen')),
            ],
            options={
                'verbose_name': 'Traslado de Bien',
                'verbose_name_plural': 'Traslados de Bienes',
                'db_table': 'inventario_trasladobien',
                'ordering': ['-fecha_traslado'],
            },
        ),
        migrations.CreateModel(
            name='EscaneoCodigoBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('codigo_patrimonial', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('mensaje_error', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que registró')),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escaneos_codigo_barra', to='bienes.bien')),
                ('traslado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos', to='traslados.trasladobien')),
            ],
            options={
                'verbose_name': 'Escaneo de Código de Barra',
                'verbose_name_plural': 'Escaneos de Códigos de Barras',
                'db_table': 'inventario_escaneocodigobarra',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
