# Generated by Django 6.0.3 on 2026-03-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion_baja', models.CharField(max_length=100, verbose_name='Resolución de Baja')),
                ('fecha_resolucion', models.DateField(verbose_name='Fecha Resolución')),
                ('causal_baja', models.CharField(choices=[('DESTRUCCION_SINIESTRO', 'DESTRUCCIÓN O SINIESTRO'), ('ENFERMEDAD_INCURABLE', 'ENFERMEDAD INCURABLE'), ('ESTADO_EXCEDENCIA', 'ESTADO DE EXCEDENCIA'), ('FALLECIMIENTO_MUERTE', 'FALLECIMIENTO O MUERTE'), ('FALTANTE_SANEAMIENTO', 'FALTANTE - SANEAMIENTO'), ('LESION_GRAVE', 'LESION GRAVE'), ('MANTENIMIENTO_REPARACION', 'MANTENIMIENTO O REPARACIÓN ONEROSA'), ('OBSOLENCIA_TECNICA', 'OBSOLENCIA TECNICA'), ('PERDIDA_ROBO', 'PERDIDA: ROBO O SUSTRACCION'), ('REEMBOLSO_REPOSICION', 'REEMBOLSO O REPOSICIÓN'), ('OTRO_CAUSAL', 'OTRO CAUSAL')], max_length=30, verbose_name='Causal de Baja')),
                ('documento_sbn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc. SBN N°')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que registró')),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baja', to='bienes.bien', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Baja de Bien',
                'verbose_name_plural': 'Bajas de Bienes',
                'db_table': 'inventario_bajabien',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
