# Generated by Django 6.0.3 on 2026-03-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Municipalidad Distrital de José Luis Bustamante y Rivero', max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
                'db_table': 'inventario_entidad',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_propiedad', models.CharField(choices=[('ESTATAL', 'Estatal'), ('PRIVADA', 'Privada'), ('ALQUILADO', 'Alquilado')], default='ESTATAL', max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (m2)')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='N°')),
                ('manzana', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mz')),
                ('lote', models.CharField(blank=True, max_length=10, null=True, verbose_name='Lte')),
                ('departamento', models.CharField(default='Arequipa', max_length=100)),
                ('provincia', models.CharField(default='Arequipa', max_length=100)),
                ('distrito', models.CharField(default='José Luis Bustamante y Rivero', max_length=100)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='organizacion.entidad')),
            ],
            options={
                'verbose_name_plural': 'Locales',
                'db_table': 'inventario_local',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(blank=True, max_length=20, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='organizacion.local')),
            ],
            options={
                'db_table': 'inventario_area',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oficinas', to='organizacion.area')),
            ],
            options={
                'db_table': 'inventario_oficina',
            },
        ),
        migrations.CreateModel(
            name='UbicacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Piso')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle')),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_fisicas', to='organizacion.area')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_fisicas', to='organizacion.local')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_fisicas', to='organizacion.oficina')),
            ],
            options={
                'verbose_name': 'Ubicación Física',
                'verbose_name_plural': 'Ubicaciones Físicas',
                'db_table': 'inventario_ubicacionfisica',
                'ordering': ['local__nombre', 'area__nombre', 'oficina__nombre', 'piso', 'detalle'],
            },
        ),
    ]
