"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Agregar la carpeta apps/ al path de Python
sys.path.insert(0, str(BASE_DIR / 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wmhcvb0rcg(v7ugj0&afrzz7)0_ort(cly*4o$+9kzy7a10l^w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'organizacion',
    'personal',
    'catalogos',
    'bienes',
    'bajas',
    'traslados',
    'reportes',
    'inventario',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Exige sesión iniciada en TODO el sistema. Las pocas vistas públicas
    # (login) se marcan con @login_not_required. Debe ir DESPUÉS de
    # AuthenticationMiddleware.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "dbInventario",
        "USER": "pc1",
        "PASSWORD": "0969",
        "HOST": "10.0.1.2",
        "PORT": "1433",
        "OPTIONS": {
            "driver": "ODBC Driver 13 for SQL Server",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================
# Autenticación / Control de acceso
# =============================================================
# A dónde se redirige al usuario sin sesión (LoginRequiredMiddleware lo usa).
LOGIN_URL = 'login'
# A dónde se va tras iniciar sesión correctamente.
LOGIN_REDIRECT_URL = 'inventario:home'
# A dónde se va tras cerrar sesión.
LOGOUT_REDIRECT_URL = 'login'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# =============================================================
# Impresora de etiquetas Zebra ZT411 (ZPL)
# =============================================================
# El sistema decide cómo imprimir en este orden de prioridad:
#   1) ZEBRA_PRINTER_NAME  -> impresora USB/local instalada en Windows (recomendado).
#      Es el nombre EXACTO que aparece en "Dispositivos e impresoras"
#      (ej: 'ZDesigner ZT411-203dpi ZPL'). Imprime directo con un clic.
#   2) ZEBRA_PRINTER_IP    -> impresora en red por el puerto raw 9100.
#   3) Si ninguno está definido (o si fallan), descarga un archivo .zpl que
#      puedes previsualizar en http://labelary.com/viewer.html o enviar con
#      Zebra Setup Utilities.
ZEBRA_PRINTER_NAME = ''      # Vacío: imprime por red (IP). Ponlo solo si usas USB local.
ZEBRA_PRINTER_IP = '10.0.1.252'   # IP de la ZT411 en la red (impresión desde cualquier PC)
ZEBRA_PRINTER_PORT = 9100    # Puerto raw estándar de Zebra
ZEBRA_PRINTER_DPI = 203      # Resolución del cabezal: 203, 300 o 600 (la ZT411 estándar es 203)
# Oscuridad del cabezal (0 a 30). Como enviamos ZPL crudo, la impresora IGNORA
# la "Oscuridad" del driver de Windows: hay que fijarla aquí. Súbela si la
# impresión sale clara; bájala si las letras se manchan o se corren.
ZEBRA_PRINTER_DARKNESS = 30
# Velocidad de impresión en mm/s (None = no tocar). Imprimir más lento también
# oscurece. La ZT411 admite 51, 76, 102, 127, 152, etc.
ZEBRA_PRINTER_SPEED = None
# Tamaño del QR (magnificación de cada módulo). Como el QR lleva todos los datos
# en JSON, este es el modo de hacerlo más chico/grande SIN quitar información:
#   1 = QR pequeño (~7 mm), ocupa poco pero los cuadritos son finos -> PRUEBA el
#       escaneo con el celular; si cuesta leerlo, súbelo a 2.
#   2 = QR mediano (~13 mm), lectura más segura.
ZEBRA_QR_MAGNIFICACION = 2

# Desplazamiento GLOBAL de TODA la impresión, en mm (puede ser negativo).
# Sirve cuando el papel está montado un poco corrido y todo sale pegado a un
# lado. NO confundir con ZEBRA_LABEL_MARGEN_IZQ_MM (que es el margen interno de
# cada etiqueta): este mueve TODO el conjunto de las 2 etiquetas a la vez.
#   Positivo  -> mueve todo a la DERECHA.
#   Negativo  -> mueve todo a la IZQUIERDA.
ZEBRA_OFFSET_GLOBAL_X_MM = 0.0

# Geometría física del rollo de etiquetas (en milímetros).
# El rollo viene con varias etiquetas por fila (columnas). Cada avance del
# papel imprime una fila completa de etiquetas.
ZEBRA_LABEL_COLUMNAS = 2     # Cuántas etiquetas hay lado a lado en el rollo
ZEBRA_LABEL_ANCHO_MM = 51    # Ancho de cada etiqueta (5 cm)
ZEBRA_LABEL_ALTO_MM = 25     # Alto de cada etiqueta (2.5 cm)
ZEBRA_LABEL_GAP_MM = 3       # Separación horizontal entre las dos etiquetas (3 mm reales)
ZEBRA_LABEL_MARGEN_IZQ_MM = 6.5  # Margen izquierdo del logo/QR (súbelo si salen cortados)