# Generated by Django 6.0.3 on 2026-03-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('tasa_depreciacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vida_util_meses', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'inventario_cuentacontable',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo Genérico',
                'verbose_name_plural': 'Grupos Genéricos',
                'db_table': 'inventario_grupogenerico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_contable', models.ForeignKey(blank=True, help_text='Cuenta contable por defecto para esta clase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='catalogos.cuentacontable')),
                ('grupo_generico', models.ForeignKey(blank=True, help_text='Grupo genérico al que pertenece esta clase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='catalogos.grupogenerico')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'inventario_clase',
                'ordering': ['grupo_generico', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True, verbose_name='Denominación')),
                ('codigo_patrimonial_base', models.CharField(max_length=50, verbose_name='Código Patrimonial Base')),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denominaciones', to='catalogos.clase')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denominaciones', to='catalogos.cuentacontable')),
                ('grupo_generico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denominaciones', to='catalogos.grupogenerico')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'db_table': 'inventario_denominacion',
                'ordering': ['nombre'],
            },
        ),
    ]
