# Generated by Django 6.0.3 on 2026-03-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=10)),
                ('numero_documento', models.CharField(max_length=15, unique=True)),
                ('modalidad', models.CharField(choices=[('CAS', 'CAS'), ('728', 'D.L. 728'), ('276', 'D.L. 276'), ('LOC', 'Locación de Servicios'), ('FUN', 'Funcionario')], max_length=10)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='organizacion.area', verbose_name='Área')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='organizacion.oficina', verbose_name='Oficina')),
            ],
            options={
                'verbose_name_plural': 'Personal',
                'db_table': 'inventario_personal',
            },
        ),
    ]
